#include "vst3hosting.hpp"

#include "vst/hosting/eventlist.cpp"
#include "vst/hosting/parameterchanges.cpp"
#include "vst/hosting/module.cpp"
#include "vst/hosting/stringconvert.cpp"
#include "vst/hosting/pluginterfacesupport.cpp"
#include "vst/hosting/processdata.cpp"
#include "vst/hosting/hostclasses.cpp"
#include "vst/hosting/plugprovider.cpp"
